name: Build

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed
    branches: [main]

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest
    # Only run if lint workflow completed successfully
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build application
        run: bun run build
