name: Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest
    # Skip if commit is from GitHub Actions (semver bot) or if it's a merge commit from a PR
    if: |
      github.actor != 'github-actions[bot]' && 
      github.event.head_commit.author.email != 'action@github.com' &&
      !contains(github.event.head_commit.message, 'Merge pull request')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        run: bun run lint
