[build]
  command = "bunx nx build pwa"
  publish = "apps/pwa/dist/client"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/version.json"
  [headers.values]
    Cache-Control = "no-store"
